apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: istio-mcs
  namespace: istio-system
spec:
  template:
    spec:
      selector:
        app: istio-ingressgateway
      ports:
      - name: status-port
        port: 15021
        protocol: TCP
        targetPort: 15021
      - name: http2
        port: 80
        protocol: TCP
        targetPort: 8080
      - name: https
        port: 443
        protocol: TCP
        targetPort: 8443
      - name: tcp-istiod
        port: 15012
        protocol: TCP
        targetPort: 15012
      - name: tls
        port: 15443
        protocol: TCP
        targetPort: 15443